name: 'Pre-commit autoupdate'
description: 'Run pre-commit autoupdate and run them on all files using uv'
branding:
  icon: chevrons-up
  color: yellow
runs:
  using: "composite"
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
      with:
        version: "latest"

    - name: Run pre-commit autoupdate
      run: uvx prek update
      shell: bash
