apiVersion: github.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: github-providerconfig
  namespace: crossplane-system
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: github-provider-secret
      key: credentials
