---
apiVersion: repo.github.upbound.io/v1alpha1
kind: Repository
metadata:
  name: hello-provider-github
  namespace: crossplane-system
spec:
  forProvider:
    name: test-crossplane
    description: My awesome codebase created by crossplane
    visibility: public
    gitignoreTemplate: Terraform
    # securityAndAnalysis:
    #   - advancedSecurity:
    #     - status: enabled
    #     secretScanning:
    #     - status: disabled
    #     secretScanningPushProtection:
    #     - status: disabled
  providerConfigRef:
    name: github-providerconfig
