apiVersion: v1
kind: Secret
metadata:
  name: github-provider-secret
  namespace: crossplane-system
type: Opaque
stringData:
  credentials: "{\"token\":\"ghp_XXXXXXXXXXXXXXXXXXXXXXXX\",\"owner\":\"thatmlopsguy\"}"
