apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: {{ .Values.cluster.name }}
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 192.168.0.0/16
    serviceDomain: cluster.local
    services:
      cidrBlocks:
        - 10.128.0.0/12
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: {{ .Values.cluster.name }}-control-plane
    namespace: default
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: DockerCluster
    name: {{ .Values.cluster.name }}
    namespace: default
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: DockerCluster
metadata:
  name: {{ .Values.cluster.name }}
  namespace: default
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: DockerMachineTemplate
metadata:
  name: {{ .Values.cluster.name }}-control-plane
  namespace: default
spec:
  template:
    spec:
      extraMounts:
        - containerPath: /var/run/docker.sock
          hostPath: /var/run/docker.sock
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  name: {{ .Values.cluster.name }}-control-plane
  namespace: default
spec:
  kubeadmConfigSpec:
    clusterConfiguration:
      apiServer:
        certSANs:
          - localhost
          - 127.0.0.1
      controllerManager:
        extraArgs:
          enable-hostpath-provisioner: "true"
    initConfiguration:
      nodeRegistration:
        criSocket: /var/run/containerd/containerd.sock
        kubeletExtraArgs:
          cgroup-driver: cgroupfs
          eviction-hard: nodefs.available<0%,nodefs.inodesFree<0%,imagefs.available<0%
    joinConfiguration:
      nodeRegistration:
        criSocket: /var/run/containerd/containerd.sock
        kubeletExtraArgs:
          cgroup-driver: cgroupfs
          eviction-hard: nodefs.available<0%,nodefs.inodesFree<0%,imagefs.available<0%
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: DockerMachineTemplate
      name: {{ .Values.cluster.name }}-control-plane
      namespace: default
  replicas: {{ .Values.cluster.masterNodes }}
  version: {{ .Values.cluster.version }}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: DockerMachineTemplate
metadata:
  name: {{ .Values.cluster.name }}-md-0
  namespace: default
spec:
  template:
    spec: {}
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: {{ .Values.cluster.name }}-md-0
  namespace: default
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            cgroup-driver: cgroupfs
            eviction-hard: nodefs.available<0%,nodefs.inodesFree<0%,imagefs.available<0%
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: {{ .Values.cluster.name }}-md-0
  namespace: default
spec:
  clusterName: {{ .Values.cluster.name }}
  replicas: {{ .Values.cluster.workerNodes }}
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: {{ .Values.cluster.name }}-md-0
          namespace: default
      clusterName: {{ .Values.cluster.name }}
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: DockerMachineTemplate
        name: {{ .Values.cluster.name }}-md-0
        namespace: default
      version: {{ .Values.cluster.version }}
---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
  name: capi-setup-{{ .Values.cluster.name }}-trigger
  namespace: argocd
spec:
  template:
    spec:
      containers:
        - image: quay.io/openshift/origin-cli:4.9
          command:
            - /bin/bash
            - -c
            - |
              echo ""
              sleep $[ $(echo $RANDOM | cut -c 2) + $WAIT ]
              kubectl rollout status sts/argocd-application-controller -n argocd
              kubectl rollout status -n argo-events $(kubectl get deployment -n argo-events -l eventsource-name=webhook -o name)
              kubectl rollout status -n argo-events $(kubectl get deployment -n argo-events -l sensor-name=webhook -o name)
              sleep $[ $(echo $RANDOM | cut -c 2) + $WAIT ]
              #
              curl -X POST -H "Content-Type: application/json" http://webhook-eventsource-svc.argo-events.svc:12000/capi-setup -d \
              "{\"wait\":\"${WAIT}\", \"capi-cluster-name\":\"${CAPI_CLUSTER_NAME}\", \"capi-cp-nodes\": \"${CAPI_CP_NODES}\", \"capi-cni-yaml-url\": \"${CAPI_CNI_YAML_URL}\", \"capi-wait-timeout\":\"${CAPI_WAIT_TIMEOUT}\"}"
              sleep $[ $(echo $RANDOM | cut -c 2) + $WAIT ]
          imagePullPolicy: Always
          name: capi-setup-wf-trigger
          env:
          - name: WAIT
            value: "{{ .Values.cluster.capiSetupWait }}"
          - name: CAPI_CLUSTER_NAME
            value: "{{ .Values.cluster.name }}"
          - name: CAPI_CP_NODES
            value: "{{ .Values.cluster.masterNodes }}"
          - name: CAPI_CNI_YAML_URL
            value: "{{ .Values.cluster.capiClusterCNI }}"
          - name: CAPI_WAIT_TIMEOUT
            value: "{{ .Values.cluster.capiSetupTimeout }}"
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      serviceAccountName: argocd-application-controller
      terminationGracePeriodSeconds: 90
---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
  name: capi-{{ .Values.cluster.name }}-presync
  namespace: argocd
spec:
  template:
    spec:
      containers:
        - image: quay.io/openshift/origin-cli:4.9
          command:
            - /bin/bash
            - -c
            - |
              echo ""
              sleep $[ $(echo $RANDOM | cut -c 2) + $WAIT ]
              kubectl rollout status sts/argocd-application-controller -n argocd
              kubectl rollout status -n argo-events $(kubectl get deployment -n argo-events -l eventsource-name=webhook -o name)
              kubectl rollout status -n argo-events $(kubectl get deployment -n argo-events -l sensor-name=webhook -o name)
              sleep $[ $(echo $RANDOM | cut -c 2) + $WAIT ]
          imagePullPolicy: Always
          name: capi-setup-wf-presync
          env:
          - name: WAIT
            value: "{{ .Values.cluster.capiSetupWait }}"
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      serviceAccountName: argocd-application-controller
      terminationGracePeriodSeconds: 90
