# Site configuration
site_url: https://thatmlopsguy.github.io/dokaseca-control-plane
site_author: That MLOps Guy
site_name: Doka Seca
site_description: A comprehensive framework for bootstrapping cloud-native platforms using Kubernetes in Docker (Kind)

# Repository
repo_url: https://github.com/thatmlopsguy/dokaseca-control-plane
repo_name: dokaseca-control-plane

# Navigation
nav:
  - Overview: index.md
  - Tech Radar: tech_radar.md
  - Architecture: architecture.md
  - Getting Started:
    - Installation: getting_started/install.md
    - Repo Structure: getting_started/repo_structure.md
    - Teams and Roles: getting_started/teams.md
  - Tutorials:
    - Overview: tutorials/overview.md
  - IAM:
    - Overview: identity.md
    - Authentication: identity/authentication.md
    - Authorization: identity/authorization.md
  - Artifact Repositories: repository.md
  - Portal: portal.md
  - GitOps:
    - Overview: gitops/overview.md
    - Addons: gitops/addons.md
    - Workloads: gitops/workloads.md
  - Networking:
    - Overview: networking/overview.md
    - Ingress: networking/ingress.md
    - Gateway API: networking/gateway_api.md
    - Service Mesh: networking/service_mesh.md
    - DNS: networking/dns.md
  - Observability:
    - Introduction: observability/overview.md
    - Dashboards: observability/dashboards.md
    - Logging: observability/logging.md
    - Monitoring: observability/monitoring.md
    - Alerting: observability/alerts.md
    - Tracing: observability/tracing.md
    - Profiles: observability/profiles.md
  - Security:
    - Overview: security/overview.md
    - Certificates: security/certificates.md
    - Secrets Management: security/secrets.md
    - Policy Enforcement: security/policy.md
  - Data:
    - Databases: data/databases.md
    - Data Streams: data/streams.md
    - Data Storage: data/storage.md
    - Caching: data/cache.md
  - Machine Learning: machine_learning.md
  - Workflow Orchestration: workflows.md
  - Distributed Computing: compute.md
  - Cost Management: cost.md
  - Chaos Engineering: chaos_engineering.md
  - Testing: testing.md
  - Disaster Recovery: backup.md
  - Federation:
    - Multi Tenancy: federation/multi_tenancy.md
    - Multi Cluster: federation/multi_cluster.md
  - Platform Engineering:
    - Overview: platform_engineering/overview.md
    - Internal Developer Portal: platform_engineering/portal.md
    - Self-Service Capabilities: platform_engineering/self_service.md
  - Resources:
    - Glossary: resources/glossary.md
    - Documentation: resources/documentation.md
    - FAQ: resources/faq.md
    - Release Notes: resources/releases.md
    - Roadmap: resources/roadmap.md
    - References: resources/references.md
  - Community:
    - Contributing: community/contributing.md
    - Maintainers: community/maintainers.md
    - Governance: community/governance.md
    - Support: community/support.md
  - Runbooks:
    - Overview: runbooks/index.md
    - Incident Response: runbooks/incident_response.md
    - Onboarding: runbooks/onboarding.md
    - Offboarding: runbooks/offboarding.md
    - Maintenance: runbooks/maintenance.md
    - Scaling: runbooks/scaling.md
    - Performance Tuning: runbooks/performance_tuning.md
    - Troubleshooting: runbooks/troubleshooting.md
    - Checklists: runbooks/checklists.md
  - RFCs:
    - Overview: rfc/index.md
    - 0001 - GitOps Promotion with Kargo: rfc/0001-gitops-promotion-with-kargo.md
  - Architecture Decisions (ADRs):
    - Overview: adr/index.md
    - 0001 - Use ADRs: adr/001-use-architecture-decision-records.md
    - 0002 - External Secrets Multi-Tenancy: adr/002-external-secrets-operator-multi-tenancy.md
    - 0003 - GitOps with ArgoCD: adr/003-argocd-hub-and-spoke-configuration.md
    - 0004 - Preview Environments: adr/004-preview-env-argocd-vcluster.md
    - 0005 - KubeGreen for Energy Optimization: adr/005-kubegreen-energy-optimization.md

# Configuration
theme:
  name: "material"
  locale: en
  font: false
  favicon: assets/logos/favicon.svg
  logo: assets/logos/logo.svg
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: amber
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: amber
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
  features:
    - navigation.footer

# Plugins
plugins:
  - search
  - git-revision-date-localized:
      type: timeago
      fallback_to_build_date: true
  - git-authors
  - tech-radar:
          title_name: 'Tech Radar'
          radars_folder: 'radars'
          target_page: 'tech_radar.md'
  # TODO: Enable these plugins when ready
  # This plugin is used to generate the ADR index page
  # mkdocs-material-adr/adr
  # mkdocs-asciinema-player

# Markdown Extensions
markdown_extensions:
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets:
      check_paths: true
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji
  - pymdownx.highlight
  - toc:
      permalink: true

# Copyright
copyright: Copyright &copy; 2025-2026 That MLOps Guy

# Extra configuration
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/thatmlopsguy/dokaseca-control-plane
    - icon: fontawesome/solid/globe
      link: https://thatmlopsguy.github.io/

# Custom CSS
extra_css:
  - "assets/css/custom.css"

# Custom JS
extra_javascript:
  - https://unpkg.com/mermaid@10.6.1/dist/mermaid.min.js
