[project]
name = "dokaseca"
version = "0.1.0"
description = "Framework for bootstrapping cloud-native platforms using Kubernetes in Docker (Kind)"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "prek>=0.2.19",
]
docs = [
    "mkdocs>=1.6.1",
    "mkdocs-git-authors-plugin>=0.10.0",
    "mkdocs-git-revision-date-localized-plugin>=1.5.0",
    "mkdocs-material>=9.7.0",
    "mkdocs-material-extensions>=1.3.1",
    "mkdocs-tech-radar",
]

[tool.uv]
python-preference = "managed"
required-version = ">=0.5.0"

[tool.uv.sources]
mkdocs-tech-radar = { git = "https://github.com/thatmlopsguy/mkdocs-tech-radar.git" }

[tool.pre-commit-update]
exclude = ["gitleaks"]
