opencost:
  customPricing:
    enabled: true
    costModel:
      description: Modified prices based on your internal pricing
      CPU: 1.25
      RAM: 0.50
      storage: 0.25
  ui:
    ingress:
        enabled: true
        ingressClassName: nginx
        hosts:
          - host: opencost.k8s-homelab
            paths:
              - /
