---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: addons-kubescape
  namespace: argocd
spec:
  syncPolicy:
    preserveResourcesOnDeletion: false
  generators:
    - merge:
        mergeKeys: [server]
        generators:
          - clusters:
              values:
                addonChart: kubescape-operator
                addonChartVersion: 1.26.4
                addonChartRepository: https://kubescape.github.io/helm-charts
                addonChartNamespace: kubescape
              selector:
                matchExpressions:
                  - key: enable_kubescape
                    operator: In
                    values: ['true']
          - clusters:
              selector:
                matchLabels:
                  environment: dev
              values:
                addonChartVersion: 1.26.4
          - clusters:
              selector:
                matchLabels:
                  environment: prod
              values:
                addonChartVersion: 1.26.4
  template:
    metadata:
      name: addon-{{name}}-{{values.addonChart}}
    spec:
      project: addons
      sources:
        - repoURL: '{{metadata.annotations.addons_repo_url}}'
          targetRevision: '{{metadata.annotations.addons_repo_revision}}'
          ref: values
        - chart: '{{values.addonChart}}'
          repoURL: '{{values.addonChartRepository}}'
          targetRevision: '{{values.addonChartVersion}}'
          helm:
            releaseName: '{{values.addonChart}}'
            ignoreMissingValueFiles: true
            valueFiles:
              - $values/environments/default/addons/{{values.addonChart}}/values.yaml
              - $values/environments/{{metadata.labels.environment}}/addons/{{values.addonChart}}/values.yaml
              - $values/clusters/{{name}}/addons/{{values.addonChart}}/values.yaml
            values: |
              clusterName: {{metadata.annotations.cluster_name}}
      destination:
        namespace: '{{values.addonChartNamespace}}'
        name: '{{name}}'
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true # Big CRDs.
      # https://github.com/kubescape/helm-charts/blob/main/ArgoCDApplication.yaml
      ignoreDifferences:
          - group: core
            kind: ConfigMap
            name: ks-cloud-config
            namespace: kubescape
            jsonPointers:
              - /data
              - /metadata
          - group: batch
            kind: CronJob
            name: kubescape-scheduler
            namespace: kubescape
            jsonPointers:
              - /spec/schedule
          - group: batch
            kind: CronJob
            name: kubevuln-scheduler
            namespace: kubescape
            jsonPointers:
              - /spec/schedule
          - kind: Secret
            name: storage-ca
            namespace: kubescape
            jsonPointers:
              - /data
          - group: apiregistration.k8s.io
            kind: APIService
            name: v1beta1.spdx.softwarecomposition.kubescape.io
            jsonPointers:
              - /spec/caBundle
