apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: simple
servers: 1
agents: 2
image: rancher/k3s:v1.31.5-k3s1
options:
  k3s:
    extraArgs:
      - arg: "--disable=traefik"
        nodeFilters:
          - server:*
