apiVersion: azure.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: gcp-providerconfig
  namespace: crossplane-system
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: gcp-creds
      key: credentials
