configs:
  secret:
    argocdServerAdminPassword: "$2a$10$5vm8wXaSdbuff0m9l21JdevzXBzJFPCi8sy6OOnpZMAG.fOXL7jvO"

dex:
  enabled: false

notifications:
  enabled: false

extensions:
  enabled: true
  contents:
  - name: argo-rollouts
    url: https://github.com/argoproj-labs/rollout-extension/releases/download/v0.3.3/extension.tar
