apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-kubernetes
  namespace: crossplane-system
spec:
  package: xpkg.upbound.io/upbound/provider-kubernetes:v0.17.1
  controllerConfigRef:
    name: kubernetes-controller-config
---
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: kubernetes-controller-config
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  serviceAccountName: kubernetes-provider-cluster-admin
