#!/bin/bash

# Base domain configuration
BASE_DOMAIN="k8s-home.lab"
# Get the ingress load balancer IP
INGRESS_LB_IP=$(kubectl get svc ingress-nginx-controller -n ingress-nginx -o jsonpath='{.status.loadBalancer.ingress[0].ip}')

# Check if we got a valid IP
if [[ -z "${INGRESS_LB_IP}" ]]; then
    echo "Error: Could not retrieve ingress load balancer IP"
    exit 1
fi

# Define the domains array
SERVICE_PREFIXES=(
    "argocd"
    "grafana"
    "alertmanager"
    "prometheus"
    "zipkin"
    "opencost"
)

# Generate hosts entries
echo -e "# Generated by $(basename $0)\n"
for prefix in "${SERVICE_PREFIXES[@]}"; do
    echo "${INGRESS_LB_IP} ${prefix}.${BASE_DOMAIN}"
done
