#!/bin/bash
# This script generates hosts entries for the services deployed in the Kubernetes cluster, using the ingress load balancer IP and a base domain.
# The generated entries can be added to the /etc/hosts file for local development and testing purposes.
# See also https://www.bushart.org/resource/wildcard-dns-ip/

# Base domain configuration
BASE_DOMAIN=${BASE_DOMAIN:-"dokaseca.local"}

# Get the ingress load balancer IP
INGRESS_LB_IP=$(kubectl get svc ingress-nginx-controller -n ingress-nginx -o jsonpath='{.status.loadBalancer.ingress[0].ip}')

# Check if we got a valid IP
if [[ -z "${INGRESS_LB_IP}" ]]; then
	echo "Error: Could not retrieve ingress load balancer IP"
	exit 1
fi

# Define the domains array
SERVICE_PREFIXES=(
    "ldap"
	"argocd"
	"kargo"
	"grafana"
	"alertmanager"
	"prometheus"
	"zipkin"
	"opencost"
	"vlogs"
	"kiali"
	"jaeger"
	"keycloak"
	"devlake"
    "mlflow"
    "langfuse"
    "temporal"
    "airflow"
    "report-portal"
    "minio"
    "litmus"
    "chaos-mesh"
    "paralus"
    "hubble"
    "headlamp"
    "oneuptime"
    "harbor"
    "chartmuseum"
    "uptrace"
    "otelcollector"
    "dagster"
    "argoworkflows"
    "argorollouts"
    "tekton-dashboard"
)

# Generate hosts entries
echo -e "# Generated by $(basename $0)\n"
for prefix in "${SERVICE_PREFIXES[@]}"; do
	echo "${INGRESS_LB_IP} ${prefix}.${BASE_DOMAIN}"
done
