apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: monitoring
  name: service-monitor-kyverno-service
  labels:
    app.kubernetes.io/instance: monitoring
    heritage: Helm
    release: kube-prometheus-stack # kubectl -n monitoring get po -l "release"
spec:
  endpoints:
  - interval: 60s
    path: /metrics
    scheme: http
    targetPort: 8000
    tlsConfig:
      insecureSkipVerify: true
  namespaceSelector:
    matchNames:
    - kyverno
  selector:
    matchLabels:
      app.kubernetes.io/instance: kyverno
