apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: capi-clusters
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - clusterName: cluster1
        gitRepo: https://github.com/thatmlopsguy/k8s-homelab
        appPath: charts/capi
        appBranch: dev
      - clusterName: cluster2
        gitRepo: https://github.com/thatmlopsguy/k8s-homelab
        appPath: charts/capi
        appBranch: dev
  template:
    metadata:
      name: '{{clusterName}}-capi'
    spec:
      project: clusters
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      source:
        repoURL: '{{gitRepo}}'
        path: '{{appPath}}'
        targetRevision: '{{appBranch}}'
        helm:
          valueFiles:
            - 'values-{{clusterName}}.yaml'
      destination:
        server: https://kubernetes.default.svc
        namespace: default
