---
apiVersion: v1
kind: Service
metadata:
  name: http-echo-service
  namespace: echo
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app: http-echo
