name: Pre-commit auto-update

on:
  # every week on Sunday at midnight
  schedule:
    - cron: "0 0 * * 0"
  # on demand
  workflow_dispatch:

jobs:
  auto-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          token: ${{ secrets.PAT_TOKEN }}
          persist-credentials: true

      - uses: ./.github/actions/pre-commit-autoupdate

      - uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        if: always()
        with:
          token: ${{ secrets.PAT_TOKEN }}
          branch: update/pre-commit-hooks
          title: "ci: update pre-commit hooks"
          commit-message: "ci: update pre-commit hooks"
          body: Update versions of pre-commit hooks to latest version.
