name: Pre-commit auto-update

on:
  # every week on Sunday at midnight
  schedule:
    - cron: "0 0 * * 0"
  # on demand
  workflow_dispatch:

jobs:
  auto-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          token: ${{ secrets.PAT_TOKEN }}
          persist-credentials: true

      - uses: ./.github/actions/pre-commit-autoupdate

      - uses: peter-evans/create-pull-request@84ae59a2cdc2258d6fa0732dd66352dddae2a412 # v7.0.9
        if: always()
        with:
          token: ${{ secrets.PAT_TOKEN }}
          branch: update/pre-commit-hooks
          title: "ci: update pre-commit hooks"
          commit-message: "ci: update pre-commit hooks"
          body: Update versions of pre-commit hooks to latest version.
