name: Pre-commit auto-update

on:
  # every week on Sunday at midnight
  schedule:
    - cron: "0 0 * * 0"
  # on demand
  workflow_dispatch:

jobs:
  auto-update:
    runs-on: ubuntu-latest
    environment: ci
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          token: ${{ secrets.PAT_TOKEN }}
          persist-credentials: true

      - uses: ./.github/actions/pre-commit-autoupdate

      - uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
        if: always()
        with:
          token: ${{ secrets.PAT_TOKEN }}
          branch: update/pre-commit-hooks
          title: "ci: update pre-commit hooks"
          commit-message: "ci: update pre-commit hooks"
          body: Update versions of pre-commit hooks to latest version.
