name: Pre-commit auto-update

on:
  # every month on the first day at midnight
  # https://crontab.guru/#0_0_1_*_*
  schedule:
    - cron: "0 0 1 * *"
  # on demand
  workflow_dispatch:

jobs:
  auto-update:
    runs-on: ubuntu-latest
    environment: ci
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          token: ${{ secrets.PAT_TOKEN }}
          persist-credentials: true

      - uses: ./.github/actions/pre-commit-autoupdate

      - uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        if: always()
        with:
          token: ${{ secrets.PAT_TOKEN }}
          branch: update/pre-commit-hooks
          title: "ci: update pre-commit hooks"
          commit-message: "ci: update pre-commit hooks"
          body: Update versions of pre-commit hooks to latest version.
