---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: addons-reloader
  namespace: argocd
spec:
  syncPolicy:
    preserveResourcesOnDeletion: false
  generators:
    - merge:
        mergeKeys: [server]
        generators:
          - clusters:
              values:
                addonChart: reloader
                addonChartVersion: 1.3.0
                addonChartRepository: https://stakater.github.io/stakater-charts
              selector:
                matchExpressions:
                  - key: enable_reloader
                    operator: In
                    values: ['true']
          - clusters:
              selector:
                matchLabels:
                  environment: dev
              values:
                addonChartVersion: 1.3.0
          - clusters:
              selector:
                matchLabels:
                  environment: prod
              values:
                addonChartVersion: 1.3.0
  template:
    metadata:
      name: addon-{{name}}-{{values.addonChart}}
    spec:
      project: addons
      sources:
        - repoURL: '{{metadata.annotations.addons_repo_url}}'
          targetRevision: '{{metadata.annotations.addons_repo_revision}}'
          ref: values
        - chart: '{{values.addonChart}}'
          repoURL: '{{values.addonChartRepository}}'
          targetRevision: '{{values.addonChartVersion}}'
          helm:
            releaseName: '{{values.addonChart}}'
            ignoreMissingValueFiles: true
            valueFiles:
              - $values/environments/default/addons/{{values.addonChart}}/values.yaml
              - $values/environments/{{metadata.labels.environment}}/addons/{{values.addonChart}}/values.yaml
              - $values/clusters/{{name}}/addons/{{values.addonChart}}/values.yaml
      destination:
        namespace: '{{values.addonChart}}'
        name: '{{name}}'
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true # Big CRDs.
